### ISSUE TITLE
`class01/README.md` & `class02/README.md` table update 요청

### ISSUE THREAD

**Issue by mokiya** [kgkorchamhrd/intel-01#74]
@82lilsak & @blackcattt3 결석하신 관계로, 공지를 못받으셔서 알려드립니다.

`class01/README.md` & `class02/README.md` 파일에 본인 영문이름 및 github account를 table에 추가 후 PR 생성하시면 됩니다.

자세한 내용은 아래 참고부탁드립니다.
https://github.com/kgkorchamhrd/intel-01/milestone/1

감사합니다.

**Comment by mokiya** [comment]
@blackcattt3 작업하신 것 봤는데, merge 하셔도 됩니다. 추가로, class01/README.md & class02/README.md 파일에 있는 table도 수정부탁합니다.

예를 들어, class01\README.md & class02\README.md 두개 파일에 20 KimYoungHee (abcde) 이라고 되어 있는 부분을 본인 이름 (github account)로 수정 후 push 추가 부탁드려요.

@blackcattt3 은 20번에 @82lilsak 은 21번에 업데이트 해주시면 좋을 것 같습니다.

**Comment by blackcattt3** [comment]
I modified the class01\README.md & class02\README.md ! 
Check again please:)

**Comment by mokiya** [comment]
@blackcattt3 I've checked your patches. thanks for your prompt action!

@82lilsak I wish that you will upload your homework as quickly as possible. thanks
